# Lazy reference to IMMED
IMMED_LAZY = $(IMMED)

IMMED := im
IMMED := $(IMMED)med

# Copies the current value of IMMED
IMMED_NOW := $(IMMED)

# IMMED_LAZY will see this modification
IMMED += iate

all:
	@ echo " 'now': $(IMMED_NOW)"
	@ echo "'lazy': $(IMMED_LAZY)"
